name: "Run Python Tests"
description: "Setup and run Python tests"

inputs:
  python-version:
    description: "Python version to use"
    required: true
  test-path:
    description: "Path to the test file or directory"
    required: true
  test-name:
    description: "Name of the test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        uv venv --seed ~/test-env
        source ~/test-env/bin/activate
        uv pip install --prerelease=allow "azure-cli>=2.65.0"
        # Use -e to include examples and tests folder in the path for unit
        # tests to access them.
        uv pip install -e ".[all]"
        uv pip install pytest pytest-xdist pytest-env>=0.6 pytest-asyncio memory-profiler==0.61.0
    - name: Run tests with pytest
      shell: bash
      env:
        TEST_PATH: ${{ inputs.test-path }}
        TEST_NAME: ${{ inputs.test-name }}
      run: |
        source ~/test-env/bin/activate
        if [[ "$TEST_NAME" == "No Parallel Tests" || "$TEST_NAME" == "Event Loop Lag Tests" ]]; then
          SKYPILOT_DISABLE_USAGE_COLLECTION=1 SKYPILOT_SKIP_CLOUD_IDENTITY_CHECK=1 eval "pytest -n 0 --dist no $TEST_PATH"
        else
          SKYPILOT_DISABLE_USAGE_COLLECTION=1 SKYPILOT_SKIP_CLOUD_IDENTITY_CHECK=1 eval "pytest -n 4 --dist worksteal $TEST_PATH"
        fi
